.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" Portions extracted from /usr/include/dirent.h are:
.\"                    Copyright 1991, 1992 Free Software Foundation
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH GETDIRENTRIES 3 2022-09-09 "Linux man-pages (unreleased)"
.SH NAME
getdirentries \- get directory entries in a filesystem-independent format
.SH LIBRARY
Standard C library
.RI ( libc ", " \-lc )
.SH SYNOPSIS
.nf
.B #include <dirent.h>
.PP
.BI "ssize_t getdirentries(int " fd ", char *restrict " buf ", size_t " nbytes ,
.BI "                      off_t *restrict " basep );
.fi
.PP
.RS -4
Feature Test Macro Requirements for glibc (see
.BR feature_test_macros (7)):
.RE
.PP
.BR getdirentries ():
.nf
    Since glibc 2.19:
        _DEFAULT_SOURCE
    Glibc 2.19 and earlier:
        _BSD_SOURCE || _SVID_SOURCE
.fi
.SH DESCRIPTION
Read directory entries from the directory specified by
.I fd
into
.IR buf .
At most
.I nbytes
are read.
Reading starts at offset
.IR *basep ,
and
.I *basep
is updated with the new position after reading.
.SH RETURN VALUE
.BR getdirentries ()
returns the number of bytes read or zero when at the end of the directory.
If an error occurs, \-1 is returned, and
.I errno
is set to indicate the error.
.SH ERRORS
See the Linux library source code for details.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.ad l
.nh
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.BR getdirentries ()
T}	Thread safety	MT-Safe
.TE
.hy
.ad
.sp 1
.SH STANDARDS
Not in POSIX.1.
Present on the BSDs, and a few other systems.
Use
.BR opendir (3)
and
.BR readdir (3)
instead.
.SH SEE ALSO
.BR lseek (2),
.BR open (2)
