'\" t
.\" Copyright 2022 Alejandro Colomar <alx@kernel.org>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH index 3 (date) "Linux man-pages (unreleased)"
.SH NAME
index, rindex \- locate character in string
.SH LIBRARY
Standard C library
.RI ( libc ", " \-lc )
.SH SYNOPSIS
.nf
.B #include <strings.h>
.PP
.BI "[[deprecated]] char *index(const char *" s ", int " c );
.BI "[[deprecated]] char *rindex(const char *" s ", int " c );
.fi
.SH DESCRIPTION
.BR index ()
is identical to
.BR strchr (3).
.PP
.BR rindex ()
is identical to
.BR strrchr (3).
.PP
Use
.BR strchr (3)
and
.BR strrchr (3)
instead of these functions.
.SH STANDARDS
4.3BSD; marked as LEGACY in POSIX.1-2001.
POSIX.1-2008 removes the specifications of
.BR index ()
and
.BR rindex (),
recommending
.BR strchr (3)
and
.BR strrchr (3)
instead.
.SH SEE ALSO
.BR strchr (3),
.BR strrchr (3)
