.TH INTMAX_T 3 2021-11-02 Linux "Linux Programmer's Manual"
.SH NAME
intmax_t \- greatest-width basic integer type
.SH SYNOPSIS
.nf
.B #include stdint.h>
.PP
.BR typedef " /* ... */ " intmax_t;
.fi
.SH DESCRIPTION
A signed integer type
capable of representing any value of any basic signed integer type
supported by the implementation.
According to the C language standard, it shall be
capable of storing values in the range
.RB [ INTMAX_MIN ,
.BR INTMAX_MAX ].
.PP
The macro
.BR INTMAX_C ()
expands its argument to an integer constant of type
.IR intmax_t .
.PP
The length modifier for
.I intmax_t
for the
.BR printf (3)
and the
.BR scanf (3)
families of functions is
.BR j ;
resulting commonly in
.B %jd
or
.B %ji
for printing
.I intmax_t
values.
.SH CONFORMING TO
C99 and later; POSIX.1-2001 and later.
.SH NOTES
The following header also provides this type:
.IR <inttypes.h> .
.SH BUGS
.I intmax_t
may not be as large as extended integer types, such as
.I __int128
.SH SEE ALSO
.BR printf (3),
.BR strtoimax (3)
